---
title: "Mouse summary"
author: "Ramiro Reyes"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(mousetrap)
library(colorspace)
library(janitor)
library(scales)
library(papaja)
library(kableExtra)
library(cowplot)
library(lemon)
library(patchwork)

knitr::opts_chunk$set(echo=F, message=F, warning=F)
```

```{r base-directories}
path_root    <- dirname(dirname(dirname(rstudioapi::getActiveDocumentContext()$path)))
path_results <- file.path(path_root, "results", "datasets")

```

```{r base-data}
load(file = file.path(path_results,  "aggregated_tnorm_mouse.RData"))

```

```{r, fig.width= 7, fig.height= 4}

group_A <- c("PrRatio + RwRatio", "RwRatio", "PrRatio")
group_B <- c("EV Ratio", "SV", "PrTl + RwTl", "PrTl")

plot_tracks <- function(data, groups = "", metrics = "") {
  
  ggplot(filter(data, metric %in% metrics) %>% 
           filter(model_name %in% groups)) + 
  
    geom_hline(yintercept = seq(0, 100, 25),
             linetype = 3,
             color = rep(c(RColorBrewer::brewer.pal(9, "Greys")[5:9]), length(groups) * length(metrics)),
             alpha = 0.8) + 
  
  geom_line(aes(x = xpos,
                y = steps,
                group = level,
                color = level),
            linetype = 1,
            size = 0.5,
            alpha = 0.8) +
    
  scale_color_viridis_d(name = "Level") +
  
  coord_capped_flip() +
  
  scale_x_reverse() +
  
  facet_rep_grid(metric ~ model_name, repeat.tick.labels = T) +
  
  theme_bw() +
  
  background_grid("none")

}

```

```{r, fig.width= 7, fig.height= 4}
plot_delta_A <- plot_tracks(aggregated_tnorm_mouse_data, group_A, c("bin_delta_p", "bin_delta_r"))

plot_delta_B <- plot_tracks(aggregated_tnorm_mouse_data, group_B, c("bin_delta_p", "bin_delta_r"))

plot_ratio_A <- plot_tracks(aggregated_tnorm_mouse_data, group_A, c("bin_ratio_p", "bin_ratio_r"))

plot_ratio_B <- plot_tracks(aggregated_tnorm_mouse_data, group_B, c("bin_ratio_p", "bin_ratio_r"))

plot_ev_A <- plot_tracks(aggregated_tnorm_mouse_data, group_A, c("bin_delta_ev", "bin_ratio_ev"))

plot_ev_B <- plot_tracks(aggregated_tnorm_mouse_data, group_B, c("bin_delta_ev", "bin_ratio_ev"))

plot_sv_A <- plot_tracks(aggregated_tnorm_mouse_data, group_A, c("bin_delta_sv"))

plot_sv_B <- plot_tracks(aggregated_tnorm_mouse_data, group_B, c("bin_delta_sv"))


```

```{r, fig.height=8, fig.width=10}
layout <- c(
  area(t = 1, b = 2, l = 2, r = 29),
  area(t = 3, b = 4, l = 1, r = 30)
)

wrap_plots(plot_delta_A, plot_delta_B) + plot_layout(design = layout, guides = "collect")
```

\newpage
```{r, fig.height=8, fig.width=10}
layout <- c(
  area(t = 1, b = 2, l = 2, r = 29),
  area(t = 3, b = 4, l = 1, r = 30)
)

wrap_plots(plot_ratio_A, plot_ratio_B) + plot_layout(design = layout, guides = "collect")
```

\newpage
```{r, fig.height=8, fig.width=10}
layout <- c(
  area(t = 1, b = 2, l = 2, r = 29),
  area(t = 3, b = 4, l = 1, r = 30)
)

wrap_plots(plot_ev_A, plot_ev_B) + plot_layout(design = layout, guides = "collect")
```

\newpage
```{r, fig.height=4.5, fig.width=10}
layout <- c(
  area(t = 1, b = 1, l = 2, r = 29),
  area(t = 2, b = 2, l = 1, r = 30)
)

wrap_plots(plot_sv_A, plot_sv_B) + plot_layout(design = layout, guides = "collect")
```


